export const PODCASTLIST_LOADED = 'PODCASTLIST_LOADED';
export const PLAY_PODCAST = 'PLAY_PODCAST';
export const RESUME_PODCAST = 'RESUME_PODCAST';
export const PAUSE_PODCAST = 'PAUSE_PODCAST';
export const QUEUE_PODCAST = 'QUEUE_PODCAST';

export const CURRENT_AUTHOR_LOADED = 'CURRENT_AUTHOR_LOADED';

export const API_ERROR = 'API_ERROR';
