export const PODCASTLIST_LOADED = 'PODCASTLIST_LOADED';
export const API_ERROR = 'API_ERROR';
export const PLAY_PODCAST = 'PLAY_PODCAST';
export const RESUME_PODCAST = 'RESUME_PODCAST';
export const PAUSE_PODCAST = 'PAUSE_PODCAST';
